# Generated by Django 4.2.23 on 2025-08-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='Hunn', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
