# Generated by Django 4.2.23 on 2025-09-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
