# Generated by Django 4.2.23 on 2026-04-28 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_confirmationemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationemail',
            name='attempts_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confirmationemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmationemail',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
