# Generated by Django 4.2.23 on 2026-04-29 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_confirmationemail_attempts_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(message='Username can contain only letters, numbers and underscore', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
