# Generated by Django 4.2.23 on 2025-07-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=60)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='emails/')),
                ('status', models.CharField(choices=[('UP', 'Uploaded'), ('AN', 'Analyzing'), ('FN', 'Finished'), ('ER', 'Error')], default='UP', max_length=2)),
                ('risk_score', models.IntegerField(default=0)),
            ],
        ),
    ]
