# Generated by Django 4.2.23 on 2025-07-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishanalyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='filename',
        ),
        migrations.AddField(
            model_name='email',
            name='analys_sid',
            field=models.CharField(default='default', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
