# Generated by Django 4.2.23 on 2025-08-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phishanalyzer', '0002_remove_email_filename_email_analys_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('UP', 'Uploaded'), ('AN', 'Analyzing'), ('FN', 'Finished'), ('ER', 'Error')], default='UP', max_length=2)),
                ('risk_score', models.IntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishanalyzer.email')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('hash_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('UP', 'Uploaded'), ('AN', 'Analyzing'), ('FN', 'Finished'), ('ER', 'Error')], default='UP', max_length=2)),
                ('risk_score', models.IntegerField(default=0)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishanalyzer.email')),
            ],
        ),
    ]
