# Generated by Django 4.2.23 on 2025-08-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishanalyzer', '0003_link_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='mail',
            new_name='email',
        ),
    ]
