# Generated by Django 4.2.23 on 2025-08-19 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phishanalyzer', '0004_rename_mail_attachment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='author',
            field=models.ManyToManyField(related_name='up_emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
