# Generated by Django 4.2.23 on 2026-04-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishanalyzer', '0005_email_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
