# Generated by Django 4.2.23 on 2026-04-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishanalyzer', '0006_email_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='file',
            field=models.FileField(null=True, upload_to='emails/'),
        ),
    ]
