# Generated by Django 4.2.23 on 2026-04-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishanalyzer', '0007_alter_email_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='analysis_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='analysis_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(null=True, upload_to='attachments/'),
        ),
    ]
