# Generated by Django 4.2.23 on 2026-05-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishanalyzer', '0008_attachment_analysis_id_link_analysis_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_caption',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='email_from',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='email_to',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
