# Generated by Django 4.2.23 on 2026-05-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishanalyzer', '0009_email_email_caption_email_email_from_email_email_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email_caption',
            new_name='email_subject',
        ),
    ]
