# Generated by Django 4.2.23 on 2026-05-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishanalyzer', '0010_rename_email_caption_email_email_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='hash_sha256',
        ),
        migrations.AddField(
            model_name='link',
            name='vt_url_id',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
